- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  vars_prompt:
    - name: username
      prompt: Username?
      private: false
    - name: theme
      prompt: theme light/dark
      private: false
      default: "light"

  tasks:
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/repositories.yml
    - include_tasks: tasks/requirements.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/gnome.yml
    - include_tasks: tasks/commands.yml
    - import_tasks: tasks/dark.yml
      when: theme == "dark"
    - include_tasks: tasks/light.yml
      when: theme == "light"

