- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/repositories.yml
    - include: tasks/requirements.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
    - include: tasks/commands.yml
    - include: tasks/cron.yml
