
- name: Install python-psutil package
  apt: name=python-psutil

- name: Copy wallpaper folder
  copy: src=files/wallpapers/ dest=/home/johannes/.wallpapers/ owner=johannes group=johannes mode=600

- name: Set wallpaper
  become_user: johannes
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/johannes/.wallpapers/wallpaper01.jpeg'"

- name: Set lock screen background
  become_user: johannes
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/johannes/.wallpapers/wallpaper01.jpeg'"

- name: Spotify Nord Theme
  ansible.builtin.shell: |
    curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh
    spicetify config current_theme Sleek color_scheme Nord
    spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
    spicetify apply

- name: vim Nord Theme
  ansible.builtin.shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    echo "https://github.com/arcticicestudio/nord-vim"
